#!/bin/bash
curl -X POST -H "Content-Type: application/json" -d '{
  "id": 0,
  "agenda": {
    "id": 7,
    "doctor": {
        "id": 1,
        "user": {
            "id": 1,
            "username": "user1",
            "password": "password1",
            "name": "Elliot",
            "firstLastname": "Alderson",
            "secondLastname": "Wellick",
            "identification": "000000000",
            "email": "darayaroma@gmail.com",
            "role": "ADMINISTRATOR",
            "phoneNumber": "00000000",
            "isActive": "N",
            "isAdmin": "N",
            "passwordChanged": "N",
            "activationCode": null,
            "language": "ENGLISH",
            "profilePhoto": null,
            "version": 1
        },
        "code": "ABC",
        "idCard": 9999,
        "shiftStartTime": "13:00",
        "shiftEndTime": "21:00",
        "hourlySlots": 5,
        "version": 0
    }, 
    "agendaDate": "2020-04-17",
    "shiftStartTime": "a",
    "shiftEndTime": "b",
    "hourlySlots": 0, 
    "version": 2
  },
  "medicalAppointment": {
    "id": 4,
    "agenda": {
        "id": 7,
        "doctor": {
            "id": 1,
            "user": {
                "id": 1,
                "username": "user1",
                "password": "password1",
                "name": "Elliot",
                "firstLastname": "Alderson",
                "secondLastname": "Wellick",
                "identification": "000000000",
                "email": "darayaroma@gmail.com",
                "role": "ADMINISTRATOR",
                "phoneNumber": "00000000",
                "isActive": "N",
                "isAdmin": "N",
                "passwordChanged": "N",
                "activationCode": null,
                "language": "ENGLISH",
                "profilePhoto": null,
                "version": 1
            },
            "code": "string",
            "idCard": 0,
            "shiftStartTime": "a",
            "shiftEndTime": "b",
            "hourlySlots": 0,
            "agendas": null,
            "version": 2
        },
        "agendaDate": "2020-04-17",
        "shiftStartTime": "a",
        "shiftEndTime": "b",
        "hourlySlots": 0,
        "version": 1 
    },
    "patient": {
        "id": 1,
        "name": "daniel",
        "firstLastname": "araya",
        "secondLastname": "roman",
        "identification": "901140423",
        "phoneNumber": "86420240",
        "email": "darayaroma@gmail.com",
        "gender": "MALE",
        "birthDate": "2003-04-17",
        "version": 1
    },
    "patientCare": null, 
    "scheduledBy": {
        "id": 1,
        "username": "user1",
        "password": "password1",
        "name": "Elliot",
        "firstLastname": "Alderson",
        "secondLastname": "Wellick",
        "identification": "000000000",
        "email": "darayaroma@gmail.com",
        "role": "ADMINISTRATOR",
        "phoneNumber": "00000000",
        "isActive": "N",
        "isAdmin": "N",
        "passwordChanged": "N",
        "activationCode": null,
        "language": "ENGLISH",
        "profilePhoto": null,
        "version": 1
},
    "scheduledDate": "2024-04-17",
    "scheduledTime": "14:00",
    "state": "SCHEDULED",
    "reason": "Need appointment urgent",
    "patientPhoneNumber": "86420240",
    "patientEmail": "darayaroma@gmail.com",
    "version": 1
}, 
  "slotDate": "2023-04-05",
  "timeSlot": "b",
  "available": "AVAILABLE",
  "version": 0
}' http://localhost:8080/clinicaunaws/api/SlotsController/create